wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: fastai
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1673909240.623078
    t:
      1:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      2:
      - 1
      - 4
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      3:
      - 2
      - 23
      4: 3.8.10
      5: 0.13.9
      8:
      - 1
      - 5
